name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies (apt-get)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Setup vitasdk
        run: |
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          ./bootstrap-vitasdk.sh
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          echo "VITASDK=/usr/local/vitasdk" >> $GITHUB_ENV
          echo "PATH=$VITASDK/bin:$PATH" >> $GITHUB_ENV
          #./install-all.sh

      - name: Configure
        run: cmake -S . -B build
      
      - name: Build
        run: cmake --build build --target package
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ScePaf.zip
          path: build/*.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@main
        with:
          pattern: "*"
          path: Release
          merge-multiple: true

      - name: Checkout uploadtool
        uses: actions/checkout@v4
        with:
          repository: 'probonopd/uploadtool'
          path: 'uploadtool'

      - name: Upload Continuous Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./uploadtool/upload.sh Release/*
