name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies (apt-get)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake patch

      - name: Setup vitasdk
        run: |
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          ./bootstrap-vitasdk.sh
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          echo "VITASDK=/usr/local/vitasdk" >> $GITHUB_ENV
          echo "PATH=$VITASDK/bin:$PATH" >> $GITHUB_ENV
          #./install-all.sh

      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build
      
      - name: Build
        run: cmake --build build --target package

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/ScePaf-*.zip

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ github.run_number }}"
          prerelease: false
          title: "Build ${{ github.run_number }}"
          files: |
            build/*.zip
